version: '3'

networks:
  strategio-network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    networks:
      - strategio-network
    ports:
      - "8090:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/http.d/default.conf:/etc/nginx/http.d/default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - $PWD:/var/www/html:cached